version: '3.8'

services:
  backend:
    build:
      context: ./bkapp
      dockerfile: Dockerfile
    ports:
      - "8080:80"        # Apache HTTP
      - "8443:443"       # Apache HTTPS
    depends_on:
      - mysql
    volumes:
      - ./bkapp:/var/www/html
    networks:
      - mainapp_network  # Connect backend to the shared network

  frontend:
    build:
      context: ./feapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost
    networks:
      - mainapp_network  # Connect frontend to the shared network

  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hello
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mainapp_network  # Connect mysql to the shared network

volumes:
  mysql_data:

networks:
  mainapp_network:
    external: true  # Reference the existing external network if it exists

