pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/abdulrahmaniq7/helloppfullstack'
      }
    }

    stage('Build & Deploy') {
      steps {
        sh 'docker-compose down'
        sh 'docker-compose up --build -d'
      }
    }
  }
}

