pipeline {
  agent any

  stages {
    stage('Clean Workspace') {
      steps {
        deleteDir() // Remove old files in workspace
      }
    }

    stage('Checkout') {
      steps {
        script {
          echo "Starting Git Checkout..."
          git url: 'https://github.com/abdulrahmaniq7/helloppfullstack.git', branch: 'main'
        }
      }
    }

    stage('Create Shared Docker Network') {
      steps {
        sh 'docker network create mainapp_network || true'
      }
    }

    stage('Stop Previous Containers') {
      steps {
        // Ensure old containers are stopped
        sh 'docker-compose -f docker-compose.yml down --remove-orphans || true'
      }
    }

    stage('Remove MySQL Data Volume') {
      steps {
        // Optional: remove to re-run init.sql
        sh 'docker volume rm mainapp_mysql_data || true'
      }
    }

    stage('Build and Start Services') {
      steps {
        sh 'docker-compose -f docker-compose.yml up --build -d'
      }
    }

    stage('Verify Deployment') {
      steps {
        sh 'docker ps' // Show running containers
      }
    }
  }
}

